export default {
  login: "monir-007",
  id: 47362857,
  node_id: "MDQ6VXNlcjQ3MzYyODU3",
  avatar_url: "https://avatars0.githubusercontent.com/u/47362857?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/monir-007",
  html_url: "https://github.com/monir-007",
  followers_url: "https://api.github.com/users/monir-007/followers",
  following_url:
    "https://api.github.com/users/monir-007/following{/other_user}",
  gists_url: "https://api.github.com/users/monir-007/gists{/gist_id}",
  starred_url: "https://api.github.com/users/monir-007/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/monir-007/subscriptions",
  organizations_url: "https://api.github.com/users/monir-007/orgs",
  repos_url: "https://api.github.com/users/monir-007/repos",
  events_url: "https://api.github.com/users/monir-007/events{/privacy}",
  received_events_url: "https://api.github.com/users/monir-007/received_events",
  type: "User",
  site_admin: false,
  name: "Monir Hossain",
  company: "@github",
  blog: "monir.hossain@northsouth.edu",
  location: "Dhaka, Bangladesh",
  email: null,
  hireable: null,
  bio: "become a software developer",
  twitter_username: "monir_wahid",
  public_repos: 10,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2019-02-05T17:06:38Z",
  updated_at: "2020-09-14T18:33:37Z",
};
